{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f08c330c-e0c9-4c16-a832-b8cd499a9129",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "\n",
    "# laod\n",
    "\n",
    "def load_data(path):\n",
    "    df = pd.read_csv(path)\n",
    "    df = df.drop_duplicates()\n",
    "    return df\n",
    "\n",
    "\n",
    "\n",
    "# clean\n",
    "\n",
    "def clean_religion_dataset(df):\n",
    "\n",
    "    # keep relevant columns\n",
    "    df = df[[col for col in df.columns\n",
    "             if col.endswith(\"Total (Population)\")\n",
    "             or col in [\"Year\", \"StateNme\"]]]\n",
    "\n",
    "    # rename columns\n",
    "    df.columns = [\n",
    "        col.replace(\"- Total (Population)\", \"\")\n",
    "        .replace(\"StateNme\", \"Country\")\n",
    "        .strip()\n",
    "        for col in df.columns\n",
    "    ]\n",
    "\n",
    "    # group as necessary\n",
    "    df[\"Confus_Tao\"] = df[\"Taoism\"] + df[\"Confucianism\"]\n",
    "\n",
    "    # select columns\n",
    "    df = df[\n",
    "        [\"Year\", \"Country\", \"Christianity\", \"Judaism\",\n",
    "         \"Islam\", \"Buddhism\", \"Hindu\", \"Shinto\", \"Confus_Tao\"]\n",
    "    ]\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# country mapping---\n",
    "\n",
    "def normalize_country_names(df):\n",
    "\n",
    "    country_mapping = {\n",
    "        \"Antigua & Barbuda\": \"Antigua and Barbuda\",\n",
    "        \"Bolivia\": \"Bolivia (Plurinational State of)\",\n",
    "        \"Brunei\": \"Brunei Darussalam\",\n",
    "        \"Cape Verde\": \"Cabo Verde\",\n",
    "        \"Czech Republic\": \"Czechia\",\n",
    "        \"East Timor\": \"Timor-Leste\",\n",
    "        \"Iran\": \"Iran (Islamic Republic of)\",\n",
    "        \"Ivory Coast\": \"Côte d'Ivoire\",\n",
    "        \"Laos\": \"Lao People's Democratic Republic\",\n",
    "        \"Moldova\": \"Republic of Moldova\",\n",
    "        \"North Korea\": \"Democratic People's Republic of Korea\",\n",
    "        \"Russia\": \"Russian Federation\",\n",
    "        \"South Korea\": \"Republic of Korea\",\n",
    "        \"Syria\": \"Syrian Arab Republic\",\n",
    "        \"Tanzania\": \"United Republic of Tanzania\",\n",
    "        \"United States of America\": \"United States\",\n",
    "        \"Venezuela\": \"Venezuela (Bolivarian Republic of)\",\n",
    "        \"Vietnam\": \"Viet Nam\",\n",
    "        \"Yugoslavia\": \"Serbia\"\n",
    "    }\n",
    "\n",
    "    df[\"Country\"] = df[\"Country\"].replace(country_mapping)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "\n",
    "def clean_conflict_dataset(df):\n",
    "\n",
    "    df = df.rename(columns={\"Conflict territory\": \"Country\"})\n",
    "    df = df[[\"Year\", \"Country\"]]\n",
    "\n",
    "    # remove space after comma\n",
    "    df[\"Country\"] = df[\"Country\"].str.replace(\", \", \",\")\n",
    "\n",
    "    # split countries\n",
    "    df[\"Country\"] = df[\"Country\"].str.split(\",\")\n",
    "\n",
    "    # explode rows\n",
    "    df = df.explode(\"Country\").reset_index(drop=True)\n",
    "\n",
    "    df = df.drop_duplicates()\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# export--\n",
    "\n",
    "def export_csv(df, path):\n",
    "    df = df.reset_index(drop=True)\n",
    "    df.to_csv(path, index=False)\n",
    "\n",
    "\n",
    "# main\n",
    "\n",
    "def main():\n",
    "\n",
    "    religion_path = \"data/raw/religion.csv\"\n",
    "    country_ref_path = \"data/raw/country_reference.csv\"\n",
    "    conflict_path = \"data/raw/conflicts.csv\"\n",
    "\n",
    "    religion_clean_path = \"data/clean/clean_religions.csv\"\n",
    "    conflict_clean_path = \"data/clean/conflict_countries.csv\"\n",
    "\n",
    "    # load\n",
    "    religion_df = load_religion_data(religion_path)\n",
    "    ref_country = load_country_reference(country_ref_path)\n",
    "    conflict_df = load_conflict_data(conflict_path)\n",
    "\n",
    "    # clean\n",
    "    religion_df = clean_religion_dataset(religion_df)\n",
    "    religion_df = normalize_country_names(religion_df)\n",
    "\n",
    "    conflict_df = clean_conflict_dataset(conflict_df)\n",
    "\n",
    "    # export\n",
    "    export_csv(religion_df, religion_clean_path)\n",
    "    export_csv(conflict_df, conflict_clean_path)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "venv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
