{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "186b5ece-6b11-4b97-900c-b1b86dfd3575",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import colormaps\n",
    "\n",
    "\n",
    "# laoding\n",
    "def load_data(path):\n",
    "    df = pd.read_csv(path)\n",
    "    df = df.drop(\"column_name\", axis=1, errors=\"ignore\")\n",
    "    df.drop_duplicates(inplace=True)\n",
    "    return df\n",
    "\n",
    "\n",
    "# long format\n",
    "def create_long_format(df):\n",
    "    long_df = df.melt(\n",
    "        id_vars=[\n",
    "            \"year\",\n",
    "            \"country\",\n",
    "            \"gdp\",\n",
    "            \"un_region\",\n",
    "            \"hdi\",\n",
    "            \"conflict_present\",\n",
    "            \"population\",\n",
    "        ],\n",
    "        var_name=\"religion\",\n",
    "        value_name=\"relig_pop\",\n",
    "    )\n",
    "    return long_df\n",
    "\n",
    "\n",
    "# religious share with correction\n",
    "def compute_religious_share(long_df):\n",
    "\n",
    "    pop_percent = (\n",
    "        long_df.groupby(\n",
    "            [\"year\", \"country\", \"un_region\", \"conflict_present\"], as_index=False\n",
    "        )\n",
    "        .agg(population=(\"population\", \"mean\"), relig_pop=(\"relig_pop\", \"sum\"))\n",
    "    )\n",
    "\n",
    "    # prevent relig_pop > population\n",
    "    pop_percent[\"relig_pop\"] = pop_percent[[\"relig_pop\", \"population\"]].min(axis=1)\n",
    "\n",
    "    pop_percent[\"percent_pop\"] = pop_percent[\"relig_pop\"] / pop_percent[\"population\"]\n",
    "\n",
    "    return pop_percent\n",
    "\n",
    "\n",
    "# group by region and mean\n",
    "def compute_region_trends(pop_percent):\n",
    "\n",
    "    pop_percent_region = (\n",
    "        pop_percent.groupby([\"year\", \"un_region\"], as_index=False)[\"percent_pop\"].mean()\n",
    "    )\n",
    "\n",
    "    return pop_percent_region\n",
    "\n",
    "\n",
    "\n",
    "# line chart and non continuous colors\n",
    "\n",
    "def plot_religious_share(pop_percent_region):\n",
    "\n",
    "    n = pop_percent_region[\"un_region\"].nunique()\n",
    "    colors = colormaps[\"turbo\"](np.linspace(0, 1, n))\n",
    "\n",
    "    plt.figure(figsize=(14, 6))\n",
    "\n",
    "    sns.lineplot(\n",
    "        data=pop_percent_region,\n",
    "        x=\"year\",\n",
    "        y=\"percent_pop\",\n",
    "        hue=\"un_region\",\n",
    "        palette=colors,\n",
    "    )\n",
    "\n",
    "    plt.title(\"Evolution of Religious Share by Region\")\n",
    "    plt.ylabel(\"Religious Population Share\")\n",
    "    plt.xlabel(\"Year\")\n",
    "\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "# wide format religion distribution for stacked bar chart\n",
    "def religion_distribution(long_df):\n",
    "\n",
    "    mean_relig = (\n",
    "        long_df.groupby([\"un_region\", \"religion\"], as_index=False)[\"relig_pop\"].mean()\n",
    "    )\n",
    "\n",
    "    pivot_relig = mean_relig.pivot(\n",
    "        index=\"un_region\", columns=\"religion\", values=\"relig_pop\"\n",
    "    ).fillna(0)\n",
    "\n",
    "    return pivot_relig\n",
    "\n",
    "\n",
    "# main\n",
    "def main():\n",
    "\n",
    "    path = \"data/clean/final_dataset.csv\"\n",
    "\n",
    "    df = load_data(path)\n",
    "\n",
    "    long_df = create_long_format(df)\n",
    "\n",
    "    pop_percent = compute_religious_share(long_df)\n",
    "\n",
    "    pop_percent_region = compute_region_trends(pop_percent)\n",
    "\n",
    "    plot_religious_share(pop_percent_region)\n",
    "\n",
    "    religion_dist = religion_distribution(long_df)\n",
    "\n",
    "    print(religion_dist.head())\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "venv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
